-- AlterTable
ALTER TABLE "Board" ALTER COLUMN "createdAt" SET DEFAULT NOW(),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Proposition" ALTER COLUMN "createdAt" SET DEFAULT NOW(),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Vote" ALTER COLUMN "createdAt" SET DEFAULT NOW(),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);
